arithmetization/src/main/java/net/consensys/linea/zktracer/ZkTracer.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/TxTrace.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/StackFragment.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/hub/CallEmptyNoStopTest.java, arithmetization/src/test/java/net/consensys/linea/zktracer/testing/BytecodeCompiler.java, arithmetization/src/test/java/net/consensys/linea/zktracer/testing/ToyExecutionEnvironment.java
=> fix: do not trace code-less frames

arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/MxpTrace.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/Trace.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlp_txrcpt/RlpTxrcpt.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlp_txrcpt/RlpTxrcptColumns.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlp_txrcpt/Trace.java
=> feat: get rid of SetRelative

arithmetization/src/main/java/net/consensys/linea/zktracer/container/stacked/list/StackedList.java, arithmetization/src/main/java/net/consensys/linea/zktracer/container/stacked/set/StackedSet.java
check stacked list collection size in list() method
fixes #343
=> check size 0 in list() method

arithmetization/src/main/java/net/consensys/linea/zktracer/ZkTraceBuilder.java, arithmetization/src/main/java/net/consensys/linea/zktracer/ZkTracer.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Aborts.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Exceptions.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/PlatformController.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Signals.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/State.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/AccountFragment.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/StackFragment.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/misc/MiscFragment.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/misc/subfragment/MxpSubFragment.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TraceSection.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/MxpData.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/txn_data/TransactionSnapshot.java, arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/Call.java, arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/GasProjection.java, arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/Sha3.java, arithmetization/src/main/resources/opcodes.yml
- Addresses #245 
- Fixes reference tests
=> feat: implement PHC

arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Aborts.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/CreateSection.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/NoCodeCallSection.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/WithCodeCallSection.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmu/Type4PreComputation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlpAddr/RlpAddr.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/romLex/RomLex.java
=> fix: ensure that the tracer does not alter the state

arithmetization/src/main/java/net/consensys/linea/zktracer/module/ext/Ext.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/ext/ExtOperation.java
=> perf: defer computing EXT components at trace-time

.github/workflows/gradle.yml
=> [MINOR] update cache action

arithmetization/src/main/java/net/consensys/linea/zktracer/module/Module.java
=> refactor: drop unused overload

arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/TxTrace.java
=> Use a simple "for" loop instead of a stream (in TxTrace)

arithmetization/src/main/java/net/consensys/linea/zktracer/ZkTracer.java, arithmetization/src/main/java/net/consensys/linea/zktracer/bytestheta/BaseBytes.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/ext/ExtOperation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/State.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/ext/TestDuplicatedOperations.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/hub/CallEmptyNoStopTest.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/hub/TestTwoPlusTwo.java, arithmetization/src/test/java/net/consensys/linea/zktracer/testing/BytecodeRunner.java, arithmetization/src/test/java/net/consensys/linea/zktracer/testing/ToyExecutionEnvironment.java, reference-tests/src/test/java/net/consensys/linea/CorsetBlockProcessor.java
=> fix: line count discrepancy

CHANGELOG.md, changelog.md, gradle.properties
release 0.1.2 for linea-besu release 8
=> prep release 8, v0.1.2

CHANGELOG.md, gradle.properties
=> bump next version to 0.1.3-SNAPSHOT

CHANGELOG.md, gradle.properties
=> bump version to 0.1.4-SNAPSHOT

arithmetization/src/main/java/net/consensys/linea/zktracer/module/mul/MulOperation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/shf/Res.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/wcp/WcpOperation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/types/Conversions.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/mod/ModTest.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/wcp/wcpEdgeCaseTest.java, arithmetization/src/test/java/net/consensys/linea/zktracer/testing/BytecodeCompiler.java
=> Fix/issue 456/wcp result lo

gradle/dependency-management.gradle
fix annoying gradle warning - kudos to @fab-10 for https://github.com/hyperledger/besu/pull/6241
applyMavenExclusions=false
=> [MINOR] fix annoying gradle warning "Errors occurred while build effective model"

arithmetization/src/main/java/net/consensys/linea/zktracer/module/romLex/RomLex.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/txn_data/Trace.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/txn_data/TxnData.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/rlpAddr/TestRlpAddress.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/rlpCommon/rlpRandEdgeCase.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/rlptxn/TestRandomTxns.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/stp/StpTest.java
=> fix: lookup txndata <-> wcp

arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/TxTrace.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TraceSection.java
=> perf: cache tx-specific line counter

arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCode.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/hub/TestTwoPlusTwo.java, arithmetization/src/test/java/net/consensys/linea/zktracer/testing/BytecodeCompiler.java
Introduce a way to generate test bytecode in mnemonic form. For instance:
```
BytecodeCompiler.newProgram()
.assemble("""
; Perform some addition
PUSH8  02
PUSH32 0x1234
ADD
""")
.compile()
```
=> feat: introduce a trivial assembler in `BytecodeCompiler`

arithmetization/src/main/java/net/consensys/linea/zktracer/ColumnHeader.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/FailureConditions.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/PlatformController.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/Keccak.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/L2Block.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/logData/LogData.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/logData/LogDataTrace.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/logInfo/LogInfo.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/logInfo/LogInfoTrace.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlp/txrcpt/RlpTxrcptTrace.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/stp/StpChunk.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/EcDataTest.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/bin/BinTest.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/ext/TestDuplicatedOperations.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/hub/CallEmptyNoStopTest.java, arithmetization/src/test/java/net/consensys/linea/zktracer/module/stp/StpTest.java
=> docs(copyright): fix copyright

arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/SStore.java
=> fix: invalid SStore gas computation

arithmetization/src/main/java/net/consensys/linea/zktracer/bytestheta/BaseBytes.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/add/AddOperation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/bin/BinOperation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/ext/ExtOperation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/mod/ModOperation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/mul/MulOperation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/romLex/RomChunk.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/romLex/RomLex.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/shf/ShfOperation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/trm/TrmOperation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/wcp/WcpOperation.java
=> refactor: add @EqualsAndHashCode annotations and remove corresponding methods

arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/selectors/TraceLineLimitTransactionSelector.java, arithmetization/src/main/java/net/consensys/linea/zktracer/ZkTracer.java
=> fix: check that spilling and limits file contain all counted modules

arithmetization/src/main/java/net/consensys/linea/zktracer/module/blake2fmodexpdata/Blake2fModexpDataOperation.java, arithmetization/src/main/java/net/consensys/linea/zktracer/module/blake2fmodexpdata/Blake2fModexpTraceHelper.java
Signed-off-by: Tsvetan Dimitrov <tsvetan.dimitrov@consensys.net>
=> fix(blake2f-modexp-data) missed fixes

.github/workflows/gradle.yml, README.md, native/build.sh, native/compress/build.gradle, native/compress/src/test/java/net/consensys/linea/compress/LibCompressTest.java
=> build: make the build script portable, explicit dependency on Go & GCC, test libcompress build

arithmetization/src/main/java/net/consensys/linea/bl/TransactionProfitabilityCalculator.java
fixes https://github.com/Consensys/protocol-misc/issues/882
Change the profitability formula as [described here](https://github.com/Consensys/protocol-misc/issues/882#issuecomment-1978523970)
=> Fix price adjustment in profitability formula
