- arithmetization/src/main/java/net/consensys/linea/tracegeneration/rpc/RollupGenerateConflatedTracesToFileV0.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/ZkTracer.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/DataCopy.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/Exp.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/GasProjector.java
- erroneous `EXP` exponent byte size computation
- erroneous `CODECOPY` argument parsing
> [shadow node] fixes

- arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/State.java
We noticed from CPU profiling during block production, i.e transaction evaluation in order to include them in a block that State.lineCount consumes a significant amount of CPU, related to the usage of a stream.
JMH Microbenchmarking confirmed that a simple loop is much better in this use case on a collection with 100k elements
```
Benchmark                            Mode  Cnt      Score     Error  Units
TestStreamsVsLoops.testMethodLoop    avgt   50   9976.233 ± 138.659  ns/op
TestStreamsVsLoops.testMethodStream  avgt   50  64048.445 ± 386.111  ns/op
```
> Use a simple for loop instead of a stream to improve performance

- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/LineaTransactionSelectorCliOptions.java
fixes default file name extension. File is processed as TOML since #448
> changed default limits file name to toml

- arithmetization/src/main/java/net/consensys/linea/zktracer/container/stacked/set/StackedSet.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/Mxp.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/shf/Shf.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/wcp/Wcp.java
The primary enhancement in this PR pertains to StackedSet, where we've replaced the underlying data structure, Stack, with Deque. This change significantly improves performance by eliminating the need for synchronization.
Additionally, we've revamped the construction of the collapsed stack. Rather than using an isDirty flag and rebuilding the entire collapsed set each time there's a modification, we've opted for an incremental approach. Now, the collapsed set is built each time the stacked set is altered, thereby avoiding the need to recreate the collapsed stack entirely.
We've also optimized the 'lineCount' method in some modules. Instead of using a stream and calling the 'mapToInt' method, which carries a significant overhead, we've chosen to use a simple 'for' loop. This change …
> Different performance optimizations 

- arithmetization/src/main/java/net/consensys/linea/zktracer/module/add/Add.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/add/AddOperation.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Exceptions.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TraceSection.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/mod/Mod.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/mod/ModOperation.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/Mxp.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/MxpData.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/romLex/RomChunk.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/shf/Shf.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/shf/ShfOperation.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/wcp/Wcp.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/wcp/WcpOperation.java
Many potentially costly computations are not required for line counting, and can thus be delayed to tracing time, optimizing sequencing performances.
> perf: delay computations at trace time

- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/selectors/TraceLineLimitTransactionSelector.java
- arithmetization/src/test/resources/log4j2.xml
sample output:
```
{"blockNumber":1190297,"blockHash":"0x883acaafae7eeac77625ae4ee15ae5a30f0bdce41749ccec67d3715bade24b33","traceCounts":{"ADD":18658,"BIN":2592,"BLOCK_KECCAK":229,"BLOCK_L1SIZE":8464,"BLOCK_L2L1LOGS":0,"BLOCK_TX":12,"EC_DATA":20,"EXT":9,"HUB":58439,"MMU":10,"MOD":1040,"MUL":320,"MXP":8571,"PRECOMPILE_BLAKE2F":0,"PRECOMPILE_ECADD":0,"PRECOMPILE_ECMUL":0,"PRECOMPILE_ECPAIRING":0,"PRECOMPILE_ECPAIRING_WEIGHTED":0,"PRECOMPILE_ECRECOVER":1,"PRECOMPILE_MODEXP":0,"PRECOMPILE_RIPEMD":0,"PRECOMPILE_SHA2":0,"PUB_LOG":62,"PUB_LOG_INFO":89,"RLP_ADDR":7,"RLP_TXN":7076,"RLP_TXRCPT":1572,"ROM":578418,"ROM_LEX":67,"SHF":1952,"TRM":439,"TXN_DATA":109,"WCP":14028}}
```
using a log4j2 configuration like this one:
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO"> …
```
> Log ZkTracer counters for every produced block

- .github/workflows/gradle.yml
Directly download corset binary release instead of building it from scratch every time.
This should spare 3-5 minutes per test CI cycle.
> ci: use Corset releases

- arithmetization/src/main/java/net/consensys/linea/zktracer/module/Module.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/State.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/L2Block.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlp/txrcpt/RlpTxrcpt.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/txn_data/TxnData.java
Minor: avoid ambiguity in status boolean.
> fix: the hub should trace its transactions in the correct order

- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/selectors/LineaTransactionSelector.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/selectors/ProfitableTransactionSelector.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/selectors/TraceLineLimitTransactionSelector.java
In case we hit one of the module limits, then the summary log at the end is wrong since it contains also the last not selected tx, we just need to use prevCumulatedLineCount instead of currCumulatedLineCount, since it the var that contains the counts of the selected txs. prevCumulatedLineCount renamed to consolidatedCumulatedLineCount to reflect that.
> Fix log of line counts in case of block limit reached + minor changes

- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/LineaTransactionSelectorCliOptions.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/LineaTransactionSelectorConfiguration.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/selectors/LineaTransactionSelector.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/selectors/ProfitableTransactionSelector.java
- arithmetization/src/test/java/net/consensys/linea/sequencer/txselection/ProfitableTransactionSelectorTest.java
Add the `--plugin-linea-adjust-tx-size` option to adjust the tx size used to calculate the profitability of a tx during block creation.
By default the value is `-45`
> Add the possibility to adjust the tx size in the profitability formula

- arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/ModexpEffectiveCall.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/modexpdata/ModexpData.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/modexpdata/ModexpDataOperation.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/modexpdata/Trace.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCode.java
- gradle/trace-files.gradle
Resolves: #288 
Signed-off-by: Tsvetan Dimitrov <tsvetan.dimitrov@consensys.net>
> feat(modexp-data): implement MODEXP_DATA module

- acceptance-tests/src/test/java/linea/plugin/acc/test/LineaPluginTestBase.java
- acceptance-tests/src/test/java/linea/plugin/acc/test/ProfitableTransactionTest.java
- acceptance-tests/src/test/java/linea/plugin/acc/test/rpc/linea/EstimateGasTest.java
- arithmetization/build.gradle
- arithmetization/src/main/java/net/consensys/linea/AbstractLineaRequiredPlugin.java
- arithmetization/src/main/java/net/consensys/linea/AbstractLineaSharedOptionsPlugin.java
- arithmetization/src/main/java/net/consensys/linea/bl/TransactionProfitabilityCalculator.java
- arithmetization/src/main/java/net/consensys/linea/config/LineaTransactionSelectorCliOptions.java
- arithmetization/src/main/java/net/consensys/linea/config/LineaTransactionSelectorConfiguration.java
- arithmetization/src/main/java/net/consensys/linea/config/LineaTransactionValidatorCliOptions.java
- arithmetization/src/main/java/net/consensys/linea/config/LineaTransactionValidatorConfiguration.java
- arithmetization/src/main/java/net/consensys/linea/rpc/linea/LineaEndpointServicePlugin.java
- arithmetization/src/main/java/net/consensys/linea/rpc/linea/LineaEstimateGas.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/LineaTransactionSelectorFactory.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/LineaTransactionSelectorPlugin.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/selectors/LineaTransactionSelector.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/selectors/ProfitableTransactionSelector.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txselection/selectors/TraceLineLimitTransactionSelector.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txvalidation/LineaTransactionValidator.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txvalidation/LineaTransactionValidatorFactory.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txvalidation/LineaTransactionValidatorPlugin.java
- arithmetization/src/test/java/net/consensys/linea/sequencer/txselection/selectors/ProfitableTransactionSelectorTest.java
- arithmetization/src/test/java/net/consensys/linea/sequencer/txvalidation/LineaTransactionValidatorTest.java
Implements https://github.com/Consensys/protocol-misc/issues/867
This requires the update Linea Besu from this PR https://github.com/Consensys/linea-besu/pull/36
The estimate gas logic is taken from the standard `eth_estimateGas` method.
New options:
- `plugin-linea-estimate-gas-min-margin` implements: MINIMUM_MARGIN_ESTIMATE_GAS to recommend a specific gas price when using linea_estimateGas in the frontend nodes (Default "1.0")
- `plugin-linea-tx-compression-ratio` The ratio between tx serialized size and its compressed size (Default 5)
Some refactor of the way cli options and configuration are managed in the plugin, since now some of the options are used by multiple plugins and so that required to make them shared.
The profitability calculator has been moved to a class so it can be also …
> Linea estimate gas endpoint

- acceptance-tests/build.gradle
- acceptance-tests/src/test/java/linea/plugin/acc/test/rpc/linea/EstimateGasTest.java
- arithmetization/src/main/java/net/consensys/linea/AbstractLineaSharedOptionsPlugin.java
- arithmetization/src/main/java/net/consensys/linea/config/LineaTransactionValidatorConfiguration.java
- arithmetization/src/main/java/net/consensys/linea/rpc/linea/LineaEstimateGas.java
- gradle/dist.gradle
Fixes https://github.com/Consensys/zkevm-monorepo/issues/2420
now it is the same of the standard eth_estimateGas and you can just pass from, the problem was in the tx size calculation where some fields were null, and I just set them to default values when not present
> Fix for NoSuchElementException when not passing the gasPrice param

- arithmetization/src/main/java/net/consensys/linea/rpc/linea/LineaEstimateGas.java
This is a safe net to avoid that the estimated priority fee + base fee returned can be less than the current min gas price
> Avoid returing an estimated priority fee that is less than the min gas price

- arithmetization/src/main/java/net/consensys/linea/AbstractLineaSharedOptionsPlugin.java
- native/compress/build.gradle
- native/compress/src/main/java/net/consensys/linea/compress/LibCompress.java
- native/compress/src/test/java/net/consensys/linea/compress/LibCompressTest.java
LibCompress needs to use the classloader that knows about the plugin location when reading the native lib from the resources.
Use of log to print native lib loading status.
> Use the right classloader to load the native library

- arithmetization/src/main/java/net/consensys/linea/blockcapture/reapers/AddressReaper.java
- arithmetization/src/main/java/net/consensys/linea/blockcapture/reapers/Reaper.java
- arithmetization/src/main/java/net/consensys/linea/blockcapture/reapers/StorageReaper.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/ZkTracer.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java
Dropping failing transactions initial state is plain stupid, as they will fail **due to** their initial state.
> fix: do not prune failing transactions from the replays

- acceptance-tests/src/test/java/linea/plugin/acc/test/rpc/linea/EstimateGasCompatibilityModeTest.java
- acceptance-tests/src/test/java/linea/plugin/acc/test/rpc/linea/EstimateGasTest.java
- arithmetization/src/main/java/net/consensys/linea/AbstractLineaSharedOptionsPlugin.java
- arithmetization/src/main/java/net/consensys/linea/config/LineaRpcCliOptions.java
- arithmetization/src/main/java/net/consensys/linea/config/LineaRpcConfiguration.java
- arithmetization/src/main/java/net/consensys/linea/rpc/linea/LineaEndpointServicePlugin.java
- arithmetization/src/main/java/net/consensys/linea/rpc/linea/LineaEstimateGas.java
Fixes https://github.com/Consensys/protocol-misc/issues/881
When the new option `plugin-linea-estimate-gas-compatibility-mode-enabled` is set to `true` then the `linea_estimateGas` API, instead of returning the result of the profitability formula, returns the min mineable gas price. By default the flag is set to `false`.
> linea_estimateGas compatibility switch

- arithmetization/src/main/java/net/consensys/linea/zktracer/ZkTracer.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/transients/OperationAncillaries.java
- arithmetization/src/main/java/net/consensys/linea/zktracer/types/MemorySpan.java
Fixes #533 
```
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"tracesEngineVersion": "0.1.4-SNAPSHOT",
"blockNumber": 296518,
"tracesCounters": {
"EXT": 8,
[...] // many erroneous counters
}
}
}
// HTTP/1.1 200 OK
// Content-Type: application/json
```
```
{
"jsonrpc": "2.0",
"id": 1,
"error": {
"code": -32603,
"message": "Plugin internal error",
"data": "Exceptions triggered while tracing: <exception messages here>"
}
}
// HTTP/1.1 200 OK
// Content-Type: application/json
```
> fix: gather & re-throw tracing exceptions

- README.md
- native/Dockerfile-win-dockcross
- native/compress/build.gradle
- native/wsl.sh
Native lib for Windows are built using WSL2 and Docker cross compile images
> Build native lib on Windows

- acceptance-tests/src/test/java/linea/plugin/acc/test/rpc/linea/EstimateGasCompatibilityModeTest.java
- acceptance-tests/src/test/java/linea/plugin/acc/test/rpc/linea/EstimateGasTest.java
- arithmetization/src/main/java/net/consensys/linea/config/LineaRpcCliOptions.java
- arithmetization/src/main/java/net/consensys/linea/config/LineaRpcConfiguration.java
- arithmetization/src/main/java/net/consensys/linea/rpc/linea/LineaEstimateGas.java
- gradle/dependency-management.gradle
Fixes https://github.com/Consensys/protocol-misc/issues/897
New option `plugin-linea-estimate-gas-compatibility-mode-multiplier` (default `1.2`) that when `plugin-linea-estimate-gas-compatibility-mode-enabled=true` multiply the minPriorityFeePerGas by that value before it is returned
> linea_estimateGas compatibility mode multiplier

- arithmetization/src/main/java/net/consensys/linea/AbstractLineaSharedOptionsPlugin.java
- arithmetization/src/main/java/net/consensys/linea/config/LineaTransactionPoolValidatorCliOptions.java
- arithmetization/src/main/java/net/consensys/linea/config/LineaTransactionPoolValidatorConfiguration.java
- arithmetization/src/main/java/net/consensys/linea/rpc/linea/LineaEndpointServicePlugin.java
- arithmetization/src/main/java/net/consensys/linea/rpc/linea/LineaEstimateGas.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txpoolvalidation/LineaTransactionPoolValidatorFactory.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txpoolvalidation/LineaTransactionPoolValidatorPlugin.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txpoolvalidation/validators/AllowedAddressValidator.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txpoolvalidation/validators/CalldataValidator.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txpoolvalidation/validators/GasLimitValidator.java
- arithmetization/src/main/java/net/consensys/linea/sequencer/txpoolvalidation/validators/ProfitabilityValidator.java
- arithmetization/src/test/java/net/consensys/linea/sequencer/txpoolvalidation/validators/AllowedAddressValidatorTest.java
- arithmetization/src/test/java/net/consensys/linea/sequencer/txpoolvalidation/validators/CalldataValidatorTest.java
- arithmetization/src/test/java/net/consensys/linea/sequencer/txpoolvalidation/validators/GasLimitValidatorTest.java
- arithmetization/src/test/java/net/consensys/linea/sequencer/txpoolvalidation/validators/ProfitabilityValidatorTest.java
Just renaming `TransactionValidator` to `TransactionPoolValidator` to make it clear that the validation is only applied when a tx is evaluated in the txpool
> Rename to TransactionPoolValidator to make it clear it only apply to the txpool
